// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "npx tsx ./prisma/seed.ts",
  },
  datasource: {
    // For Prisma v7 CLI (migrate/db push), we MUST use the direct database connection
    // because Supabase connection pooling (port 6543) does not support schema alterations. 
    url: process.env["DIRECT_URL"],
  },
});
